version: '3'
services:
  app:
    build: .
    env_file: .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db
    command: /start-reload.sh
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: <YOUR_DB_NAME>